apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
      - name: bot-service
        image: bot_service_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://123.60.187.205:3307/unigpt_bot"
        - name: DB_USERNAME
          value: "unigpt"
        - name: DB_PASSWORD
          value: "unigpt"
        - name: USER_SERVICE_URL
          value: "http://user-service:8080"
        - name: CHAT_SERVICE_URL
          value: "http://chat-service:8080"
        - name: PLUGIN_SERVICE_URL
          value: "http://plugin-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: NodePort