apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: chat_service_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://123.60.187.205:3308/unigpt_chat"
        - name: DB_USERNAME
          value: "unigpt"
        - name: DB_PASSWORD
          value: "unigpt"
        - name: POSTGRES_HOST
          value: "postgresql_db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_USER
          value: "bleaves"
        - name: POSTGRES_PASSWORD
          value: "bleaves"
        - name: OPENAI_API_BASE_URL
          value: "https://api.openai.com"
        - name: OPENAI_API_KEY
          value: "sk-j101-s9eW29r08H38nPRyMia7T3BlbkFJom4ndaHHCjhWkRRp3lsG"
        - name: CLAUDE_API_BASE_URL
          value: "https://api.claude-Plus.top"
        - name: CLAUDE_API_KEY
          value: "sk-JAuS27IqZB15lJST6a76A0111e2d4eEb9d7aD0Bd34F20271"
        - name: LLAMA_API_BASE_URL
          value: "https://xqtd520qidong.com"
        - name: LLAMA_API_KEY
          value: "sk-hMdKUabqMiRM247Y2b23B02e8f484a9198D27cA2D66eAe4d"
        - name: KIMI_API_BASE_URL
          value: "https://api.moonshot.cn"
        - name: KIMI_API_KEY
          value: "sk-xn7ruJ2a0MYLAcheud6qVC87I6mx7b0wpFODccHCDW8oUWMg"
        - name: USER_SERVICE_URL
          value: "http://user-service:8080"
        - name: BOT_SERVICE_URL
          value: "http://bot-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: NodePort