apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: unigpt-frontend-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_IP
          value: "123.60.187.205"
        - name: REACT_APP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontendS
  ports:
    - name: frontend-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
  type: NodePort