apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-service
  template:
    metadata:
      labels:
        app: plugin-service
    spec:
      containers:
      - name: plugin-service
        image: plugin_service_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://123.60.187.205:3309/unigpt_plugin"
        - name: DB_USERNAME
          value: "unigpt"
        - name: DB_PASSWORD
          value: "unigpt"
        - name: USER_SERVICE_URL
          value: "http://user-service:8080"
        - name: BOT_SERVICE_URL
          value: "http://bot-service:8080"
        - name: CHAT_SERVICE_URL
          value: "http://chat-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-service
spec:
  selector:
    app: plugin-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: NodePort